# Tutorial for the core API

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from copy import deepcopy

## Setup parameters

In [3]:
from rashomon import hasse

There are 3 features
- Feature 1 takes on four values, {0, 1, 2, 3}
- Feature 2 takes on three values, {0, 1, 2}
- Feature 3 takes on three values, {0, 1, 2}

In [4]:
M = 3
R = np.array([4, 3, 3])

First, we find all the profiles corresponding to this setup. For the profiles, only the number of features matters.

In [5]:
num_profiles = 2**M
profiles, profile_map = hasse.enumerate_profiles(M)

print("Profiles")
print(profiles)

print("\nMap from each profile tuple to its index in `profiles` list")
print(profile_map)

Profiles
[(0, 0, 0), (0, 0, 1), (0, 1, 0), (0, 1, 1), (1, 0, 0), (1, 0, 1), (1, 1, 0), (1, 1, 1)]

Map from each profile tuple to its index in `profiles` list
{(0, 0, 0): 0, (0, 0, 1): 1, (0, 1, 0): 2, (0, 1, 1): 3, (1, 0, 0): 4, (1, 0, 1): 5, (1, 1, 0): 6, (1, 1, 1): 7}


Next, we find all the possible feature combinations (i.e., policies) in our example.

In [6]:
all_policies = hasse.enumerate_policies(M, R)
num_policies = len(all_policies)

print(f"All {num_policies} policies")
print(all_policies)

All 36 policies
[(np.int64(0), np.int64(0), np.int64(0)), (np.int64(0), np.int64(0), np.int64(1)), (np.int64(0), np.int64(0), np.int64(2)), (np.int64(0), np.int64(1), np.int64(0)), (np.int64(0), np.int64(1), np.int64(1)), (np.int64(0), np.int64(1), np.int64(2)), (np.int64(0), np.int64(2), np.int64(0)), (np.int64(0), np.int64(2), np.int64(1)), (np.int64(0), np.int64(2), np.int64(2)), (np.int64(1), np.int64(0), np.int64(0)), (np.int64(1), np.int64(0), np.int64(1)), (np.int64(1), np.int64(0), np.int64(2)), (np.int64(1), np.int64(1), np.int64(0)), (np.int64(1), np.int64(1), np.int64(1)), (np.int64(1), np.int64(1), np.int64(2)), (np.int64(1), np.int64(2), np.int64(0)), (np.int64(1), np.int64(2), np.int64(1)), (np.int64(1), np.int64(2), np.int64(2)), (np.int64(2), np.int64(0), np.int64(0)), (np.int64(2), np.int64(0), np.int64(1)), (np.int64(2), np.int64(0), np.int64(2)), (np.int64(2), np.int64(1), np.int64(0)), (np.int64(2), np.int64(1), np.int64(1)), (np.int64(2), np.int64(1), np.int64(2)),

## Partition matrix

In [7]:
from rashomon import extract_pools

We will look only at the (1, 1, 1) profile for the purpose of illustration.

In [8]:
policies_111 = [x for x in all_policies if x[0] > 0 and x[1] > 0 and x[2] > 0]
policies_111

[(np.int64(1), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(1), np.int64(2)),
 (np.int64(1), np.int64(2), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(2)),
 (np.int64(2), np.int64(1), np.int64(1)),
 (np.int64(2), np.int64(1), np.int64(2)),
 (np.int64(2), np.int64(2), np.int64(1)),
 (np.int64(2), np.int64(2), np.int64(2)),
 (np.int64(3), np.int64(1), np.int64(1)),
 (np.int64(3), np.int64(1), np.int64(2)),
 (np.int64(3), np.int64(2), np.int64(1)),
 (np.int64(3), np.int64(2), np.int64(2))]

Let us say that the partition is as follows:
- $\pi_1$ = {(1, 1, 1), (1, 2, 1)}
- $\pi_2$ = {(1, 1, 2), (1, 2, 2)}
- $\pi_3$ = {(2, 1, 1), (2, 2, 1), (3, 1, 1), (3, 2, 1)}
- $\pi_4$ = {(2, 1, 2), (2, 2, 2), (3, 1, 2), (3, 2, 2)}

This corresponds to the following $\Sigma$ matrix. The `np.inf` implies that that feature does not take those factor levels.

In [9]:
sigma_111 = np.array([[0, 1],
                  [1, np.inf],
                  [0, np.inf]])
sigma_111

array([[ 0.,  1.],
       [ 1., inf],
       [ 0., inf]])

This is how we extract the pools from the matrix.

In [10]:
pi_pools, pi_policies = extract_pools.extract_pools(policies_111, sigma_111)

`pi_pools` is a dictionary that maps each pool index to a list of _indices_ of feature combinations in that pool

In [11]:
pi_pools

{0: [0, 2], 1: [1, 3], 2: [4, 8, 10, 6], 3: [5, 9, 11, 7]}

`pi_policies` is a dictionary that maps each feature combination (through its index) to the index of the pool it belongs to

In [12]:
pi_policies

{0: 0, 2: 0, 1: 1, 3: 1, 4: 2, 8: 2, 10: 2, 6: 2, 5: 3, 9: 3, 11: 3, 7: 3}

`extract_pools` also has an optional argument `lattice_edges` where you provide the edges in the Hasse. If you call `extract_pools` on the same Hasse very often, it is more efficient to pre-compute the lattice edges once and pass in this argument

In [13]:
hasse_edges = extract_pools.lattice_edges(policies_111)

pi_pools, pi_policies = extract_pools.extract_pools(policies_111, sigma_111, lattice_edges=hasse_edges)

## Generate data

Since there are 4 pools, we only need to select 4 distributions for the outcome. For simplicity, say the outcomes come from $N(\mu_{\pi}, \sigma_{\pi}^2)$ with the following parameters for each pool

In [14]:
mu_111 = np.array([0, 2, 4, -2])
var_111 = np.array([1, 1, 1, 1])

Fix 50 samples per feature and generate the data

In [15]:
np.random.seed(3)

num_samples_per_feature = 50
num_data = len(policies_111) * num_samples_per_feature

X = np.zeros(shape=(num_data, M))
D = np.zeros(shape=(num_data, 1), dtype='int_')
y = np.zeros(shape=(num_data, 1))

idx_ctr = 0
for k, feature in enumerate(policies_111):
    # policy_idx = [i for i, x in enumerate(all_policies) if x == policy]

    pool_id = pi_policies[k]
    mu_i = mu_111[pool_id]
    var_i = var_111[pool_id]
    y_i = np.random.normal(mu_i, var_i, size=(num_samples_per_feature, 1))

    start_idx = idx_ctr * num_samples_per_feature
    end_idx = (idx_ctr + 1) * num_samples_per_feature

    X[start_idx:end_idx, ] = feature
    D[start_idx:end_idx, ] = k
    y[start_idx:end_idx, ] = y_i

    idx_ctr += 1

`X` is the feature matrix.

`D` tells us the feature indices i.e., `D[i, 0]` is the feature index of `X[i, ]`.

`y` is the outcome vector

In [16]:
print(X[:10,])

print(D[:10])

print(y[:10])

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
[[ 1.78862847]
 [ 0.43650985]
 [ 0.09649747]
 [-1.8634927 ]
 [-0.2773882 ]
 [-0.35475898]
 [-0.08274148]
 [-0.62700068]
 [-0.04381817]
 [-0.47721803]]


We can calculate the mean outcome of each feature through the following object. The first column contains the sums of outcomes for each feature. The second column is the count. So dividing the first column by the second lets us find the average. We keep the sums and counts separately for internal computation purposes

In [17]:
from rashomon import loss

policy_means_111 = loss.compute_policy_means(D, y, len(policies_111))
print(policy_means_111)

[[ -14.696341     50.        ]
 [ 103.83263356   50.        ]
 [   1.45837656   50.        ]
 [  95.24720387   50.        ]
 [ 221.50472005   50.        ]
 [ -92.80830557   50.        ]
 [ 189.57330566   50.        ]
 [-107.31751574   50.        ]
 [ 209.98734846   50.        ]
 [-103.75982477   50.        ]
 [ 200.56828936   50.        ]
 [ -99.03931665   50.        ]]


## Finding the Rashomon set for profile (1, 1, 1)

In [18]:
from rashomon import aggregate

%load_ext autoreload
%autoreload 2

Let us set the maximum number of pools to be $H = \infty$ and the Rashomon threshold to be $\theta = 8$ and regularization $\lambda = 1$

In [19]:
H = np.inf
theta = 8
lamb = 1

RPS_111 = aggregate.RAggregate_profile(M, R, H, D, y, theta, profile=(1, 1, 1), reg=lamb)

The output of `RAggregate_profile` is an object of type `RashomonSet`. Here are some useful things we can do with this. Observe that the true partition `sigma_111` is the second partition in the RPS and has the least loss.

In [20]:
# Show the partition matrix for each member of the RPS
for sig in RPS_111.sigma:
    print(sig)

# Count the number of pools in each Rashomon partition
print(RPS_111.pools)

[]


In [21]:
# Calculate the loss
# This needs to be done only when calling `RAggregate_profile`
# When calling the main function `RAggregate`, loss is automatically calculated
RPS_111.calculate_loss(D, y, policies_111, policy_means_111, reg=lamb)

# Print the loss for each member in the RPS
print(RPS_111.loss)

[]


Additionally, there is an internal function that manually checks every single partition to see if it belongs to the RPS.

In [22]:
RPS_111_brute_force = aggregate._brute_RAggregate_profile(M, R, H, D, y, theta, profile=(1, 1, 1), reg=lamb)

# Verify that the brute force computation matches the branch-and-bound algorithm
RPS_111_brute_force.P_hash == RPS_111.P_hash

True

## For all profiles

Fix the partition matrices and outcome parameters for all other profiles

In [23]:
# Profile (0, 0, 0)
sigma_000 = None
mu_000 = np.array([0])
var_000 = np.array([1])

# Profile (0, 0, 1)
sigma_001 = np.array([[1]])
mu_001 = np.array([-2])
var_001 = np.array([1])

# Profile (0, 1, 0)
sigma_010 = np.array([[1]])
mu_010 = np.array([1])
var_010 = np.array([1])

# Profile (0, 1, 1)
sigma_011 = np.array([[1], [0]])
mu_011 = np.array([1, -2])
var_011 = np.array([1, 1])

# Profile (1, 0, 0)
sigma_100 = np.array([[0, 1]])
mu_100 = np.array([0, 2])
var_100 = np.array([1, 1])

# Profile (1, 0, 1)
sigma_101 = np.array([[0, 1], [0, np.inf]])
mu_101 = np.array([0, 2, 1, -2])
var_101 = np.array([1, 1, 1, 1])

# Profile (1, 1, 0)
sigma_110 = np.array([[0, 1], [1, np.inf]])
mu_110 = np.array([0, -2])
var_110 = np.array([1, 1])

sigma = [sigma_000, sigma_001, sigma_010, sigma_011, sigma_100, sigma_101, sigma_110, sigma_111]
mu = [mu_000, mu_001, mu_010, mu_011, mu_100, mu_101, mu_110, mu_111]
var = [var_000, var_001, var_010, var_011, var_100, var_101, var_110, var_111]

### Find all pools for each profile

This code block does what we did previously for a single profile. Since `extract_pools` only works for indexing within a Hasse, we need to carefully map the universal indexing of features across all profiles to its corresponding index within the profile that it belongs to. This is why this code chunk appears more complicated than it actually is.

In [24]:
policies_profiles = {}
policies_profiles_masked = {}
policies_ids_profiles = {}
pi_policies = {}
pi_pools = {}
for k, profile in enumerate(profiles):

    policies_temp = [(i, x) for i, x in enumerate(all_policies) if hasse.policy_to_profile(x) == profile]
    unzipped_temp = list(zip(*policies_temp))
    policies_ids_k = list(unzipped_temp[0])
    policies_k = list(unzipped_temp[1])
    policies_profiles[k] = deepcopy(policies_k)
    policies_ids_profiles[k] = policies_ids_k

    profile_mask = list(map(bool, profile))

    # Mask the empty arms
    for idx, pol in enumerate(policies_k):
        policies_k[idx] = tuple([pol[i] for i in range(M) if profile_mask[i]])
    policies_profiles_masked[k] = policies_k

    if np.sum(profile) > 0:
        pi_pools_k, pi_policies_k = extract_pools.extract_pools(policies_k, sigma[k])
        if len(pi_pools_k.keys()) != mu[k].shape[0]:
            print(f"Profile {k}. Expected {len(pi_pools_k.keys())} pools. Received {mu[k].shape[0]} means.")
        pi_policies[k] = pi_policies_k
        # pi_pools_k has indicies that match with policies_profiles[k]
        # Need to map those indices back to all_policies
        pi_pools[k] = {}
        for x, y in pi_pools_k.items():
            y_full = [policies_profiles[k][i] for i in y]
            y_agg = [all_policies.index(i) for i in y_full]
            pi_pools[k][x] = y_agg
    else:
        pi_policies[k] = {0: 0}
        pi_pools[k] = {0: [0]}

### Generate data

Again, this repeats what we did for a single profile for all profiles.

In [25]:
def generate_data(mu, var, n_per_pol, all_policies, pi_policies, M):
    num_data = num_policies * n_per_pol
    X = np.zeros(shape=(num_data, M))
    D = np.zeros(shape=(num_data, 1), dtype='int_')
    y = np.zeros(shape=(num_data, 1))

    idx_ctr = 0
    for k, profile in enumerate(profiles):
        policies_k = policies_profiles[k]

        for idx, policy in enumerate(policies_k):
            policy_idx = [i for i, x in enumerate(all_policies) if x == policy]

            pool_id = pi_policies[k][idx]
            mu_i = mu[k][pool_id]
            var_i = var[k][pool_id]
            y_i = np.random.normal(mu_i, var_i, size=(n_per_pol, 1))

            start_idx = idx_ctr * n_per_pol
            end_idx = (idx_ctr + 1) * n_per_pol

            X[start_idx:end_idx, ] = policy
            D[start_idx:end_idx, ] = policy_idx[0]
            y[start_idx:end_idx, ] = y_i

            idx_ctr += 1

    return X, D, y

In [26]:
num_samples_per_feature = 50000

X, D, y = generate_data(mu, var, num_samples_per_feature, all_policies, pi_policies, M)
policy_means = loss.compute_policy_means(D, y, num_policies)

### Finding the Rashomon Set

In [27]:
H = np.inf
theta = 13
lamb = 1

R_set, R_profiles = aggregate.RAggregate(M, R, H, D, y, theta, reg=lamb, verbose=True)

(0, 0, 0) 12.030462425103009
Profile (0, 0, 0) has 1 objects in Rashomon set
(0, 0, 1) 12.057744867578162
Adaptive
Profile (0, 0, 1) took 0.04080390930175781 s adaptively
Profile (0, 0, 1) has 2 objects in Rashomon set
(0, 1, 0) 12.0582758451157
Adaptive
Profile (0, 1, 0) took 0.04013800621032715 s adaptively
Profile (0, 1, 0) has 2 objects in Rashomon set
(0, 1, 1) 12.114337623086165
Adaptive
Profile (0, 1, 1) took 0.21038293838500977 s adaptively
Profile (0, 1, 1) has 4 objects in Rashomon set
(1, 0, 0) 12.085844227048296
Adaptive
Profile (1, 0, 0) took 0.1400446891784668 s adaptively
Profile (1, 0, 0) has 4 objects in Rashomon set
(1, 0, 1) 12.168943514770383
Adaptive
Profile (1, 0, 1) took 0.7126388549804688 s adaptively
Profile (1, 0, 1) has 8 objects in Rashomon set
(1, 1, 0) 12.168701235927644
Adaptive
Profile (1, 1, 0) took 0.8784351348876953 s adaptively
Profile (1, 1, 0) has 8 objects in Rashomon set
(1, 1, 1) 12.335497837770925
Adaptive
Profile (1, 1, 1) took 3.8135890960693

The output of `RAggregate` is different from that of `RAggregate_profile`. For starters, the output is a tuple.

The first item `R_set` is a list. Each item in `R_set` is a list itself. The length of this list is the number of profiles. Each item in `R_set[i]` gives an index for a partition of that profile. So `R_set[i][k]` is the partition of the k-th profile in the i-th Rashomon partition in the RPS.

The second item `R_profiles` is a list whose length is the number of profiles. Each item is the `RashomonSet` object that we saw earlier. The indices in `R_set` correspond to the partitions in `R_profiles`. So the actual partition of `R_set[i][k]` is retrieved by accessing `R_profiles[k].sigma[R_set[i][k]]`.

In [28]:
R_profiles[7]

[array([[ 1.,  1.],
       [ 1., inf],
       [ 1., inf]]), array([[ 1.,  1.],
       [ 1., inf],
       [ 0., inf]]), array([[ 0.,  1.],
       [ 1., inf],
       [ 0., inf]]), array([[ 0.,  1.],
       [ 1., inf],
       [ 1., inf]]), array([[ 1.,  0.],
       [ 1., inf],
       [ 1., inf]]), array([[ 1.,  1.],
       [ 0., inf],
       [ 1., inf]])]

Now, let us see how to access these.

In [29]:
i = 3

RPS_partitions_i = R_set[i]

total_loss = 0
total_pools = 0
for k, profile in enumerate(profiles):
    print("Profile", profile)

    R_partition_i_k = R_profiles[k].sigma[RPS_partitions_i[k]]
    print("Partition")
    print(R_partition_i_k)

    # Notice that unlike the per-profile case, the loss of this partition is already pre-computed
    loss_i_k = R_profiles[k].loss[RPS_partitions_i[k]]
    print(f"Loss = {loss_i_k}")
    
    pools_i_k = R_profiles[k].pools[RPS_partitions_i[k]]
    print(f"Number of pools = {pools_i_k}")

    total_loss += loss_i_k
    total_pools += pools_i_k

    print("---")

print(f"Total loss = {total_loss}, Total number of pools = {total_pools}")

Profile (0, 0, 0)
Partition
None
Loss = 1.0276327713315392
Number of pools = 1
---
Profile (0, 0, 1)
Partition
[[1.]]
Loss = 1.0549152190530173
Number of pools = 1.0
---
Profile (0, 1, 0)
Partition
[[1.]]
Loss = 1.0554461937366306
Number of pools = 1.0
---
Profile (0, 1, 1)
Partition
[[1.]
 [1.]]
Loss = 1.3612916033997204
Number of pools = 1.0
---
Profile (1, 0, 0)
Partition
[[1. 1.]]
Loss = 1.157395257884124
Number of pools = 1.0
---
Profile (1, 0, 1)
Partition
[[ 1.  1.]
 [ 1. inf]]
Loss = 1.5540328652364819
Number of pools = 1.0
---
Profile (1, 1, 0)
Partition
[[ 1.  1.]
 [ 1. inf]]
Loss = 1.3142552442601412
Number of pools = 1.0
---
Profile (1, 1, 1)
Partition
[[ 0.  1.]
 [ 1. inf]
 [ 1. inf]]
Loss = 4.444784097194952
Number of pools = 2.0
---
Total loss = 12.969753252096606, Total number of pools = 9.0


By default `RAggregate` uses only one process. But we can parallelize finding Rashomon sets for each profile by changing the `num_workers` argument

In [30]:
import time

In [31]:
# num_workers = 1

start = time.time()
R_set1, R_profiles1 = aggregate.RAggregate(M, R, H, D, y, theta, reg=lamb, num_workers=1)
end = time.time()
elapsed = end - start

print(f"With 1 worker, RAggregate took {elapsed} s.")

With 1 worker, RAggregate took 9.390249013900757 s.


In [32]:
# num_workers = 2

start = time.time()
R_set2, R_profiles2 = aggregate.RAggregate(M, R, H, D, y, theta, reg=lamb, num_workers=2)
end = time.time()
elapsed = end - start

print(f"With 2 workers, RAggregate took {elapsed} s.")

With 2 workers, RAggregate took 7.821417808532715 s.


In [33]:
# Check whether the results are the same
print(R_set1 == R_set2)

True


The difference of 1 second seems negligible but the gains will be more substantial when there are more features.

In [34]:
R_profiles[0].P_qe

[None]

### First step: find neighbourhood of a partition

In [35]:
from __future__ import annotations
from collections import defaultdict
from dataclasses import dataclass
from typing import Callable, List, Tuple, Optional, Sequence
import numpy as np
import math, random

# --- bring your repo primitives (edit path as needed) ---
# compute_Q(D, y, sigma, policies, policy_means, reg=1, normalize=0, lattice_edges=None) -> float
from rashomon.loss import compute_Q
from rashomon.aggregate.raggregate import RAggregate          # (variant A)
from rashomon import hasse

###
# 1) State + anchor materialization
###

class ProfilePart:
    cov_ids: List[int]        # active covariate indices for THIS profile
    B: np.ndarray  

    def __init__(self, cov_ids, B):
        self.cov_ids = cov_ids
        self.B = B

State = List[ProfilePart]  # length P; each item is an (M,R) int matrix

def states_equal(a: State, b: State) -> bool:
    if len(a)!=len(b): return False
    for ap,bp in zip(a,b):
        if ap.cov_ids != bp.cov_ids: return False
        if not np.array_equal(ap.B, bp.B): return False
    return True

def build_anchor_states(R_set, R_profiles, M: int, R: int) -> List[State]:
    """
    R_set[g]: list[int] of length P (which candidate per profile)
    R_profiles[p][i]: (M,R) matrix for profile p, candidate i
    Returns: list of states; each state is [Sigma_0, ..., Sigma_{P-1}], Sigma_p ∈ ℤ^{M×R}.
    """
    P = len(R_profiles)
    anchors: List[State] = []
    profiles, profile_map = hasse.enumerate_profiles(int(math.log2(P)))
    for idx_vec in R_set:
        if len(idx_vec) != P:
            raise ValueError(f"R_set entry length {len(idx_vec)} != P={P}")
        state = []
        for p, sel in enumerate(idx_vec):
            cand = R_profiles[p].sigma[int(sel)]
            state.append(ProfilePart(cov_ids=profiles[p], B=cand))
        anchors.append(state)
        # # dedup by bytes of concatenated matrices
        # key = b"".join(S.tobytes() for S in state)
        # if key not in seen:
        #     anchors.append([S.copy() for S in state])
        #     seen.add(key)
    return anchors

# ---------- Flipping ones/zeros at one position inside a profile ----------
        
import numpy as np
from typing import List, Optional

def _unit_shift_row_neighbors(row: np.ndarray, need: Optional[int] = None) -> List[np.ndarray]:
    """
    NEW BEHAVIOR (bit flip):
      Generate neighbors by flipping exactly ONE finite entry in `row`:
      0 -> 1  or  1 -> 0.  +inf entries are NOT touched.

    Args
    ----
    row  : 1D array of length C; dtype float (may contain +inf sentinels)
    need : if provided, only columns j < need are considered flippable
           (useful when different arms have different (R_m - 2))

    Returns
    -------
    neighbors : list of 1D arrays (copies) with exactly one position flipped
    """
    r = np.asarray(row, dtype=float).ravel()
    C = r.size

    # finite positions are flippable; optionally restrict to first `need` columns
    finite = np.isfinite(r)
    if need is not None:
        mask = np.zeros(C, dtype=bool)
        mask[:int(need)] = True
        finite &= mask

    idxs = np.flatnonzero(finite) # which entries are not inf and therefore can be flipped
    if idxs.size == 0:
        return []

    nbrs = []
    for j in idxs:
        new_r = r.copy()
        new_r[j] = 0.0 if (new_r[j] > 0.0) else 1.0
        nbrs.append(new_r)
    return nbrs

def profile_part_neighbors_ubs(part: ProfilePart, min_len=1) -> List[ProfilePart]:
    '''Neighbour of a profile, iterating over all rows of B, extract neighbors of every row'''
    C, R = part.B.shape
    out=[]
    for r in range(C): # repeat of finding neighbour for each row
        b = part.B[r,:]
        # while math.isinf(b[-1]): # get rid of inf to compute boundary
        #     b = b[:-1]
        # if len(b)<=1: continue
        
        for nb_row in _unit_shift_row_neighbors(b):
            if nb_row is None: continue
            nbB = part.B.copy()
            # while (len(nbB[r,:]) > len(nb_row)): # pad inf back to keep format
            #     nb_row.append(float('inf'))
            nbB[r,:] = nb_row
            out.append(ProfilePart(cov_ids=list(part.cov_ids), B=nbB))
    return out

def _copy_B(B):
    if B is None:
        return None
    if isinstance(B, np.ndarray):
        return B.copy()
    if isinstance(B, (list, tuple)):
        return [np.asarray(r).copy() for r in B]
    # fallback: try to array-copy
    return np.asarray(B).copy()

def _state_signature(s): # for deduplication
    sig=[]
    for pp in s:
        cov = None if pp.cov_ids is None else tuple(pp.cov_ids)  # ensure tuple
        if pp.B is None:
            Bsig = ('None',)
        else:
            A = np.asarray(pp.B)
            Bsig = (A.shape, tuple(A.ravel()))
        sig.append((cov, Bsig))
    return tuple(sig)

def state_neighbors_ubs(state: List[ProfilePart], min_len: int = 1) -> List[List[ProfilePart]]:
    """Neighborhood of a state, iterate over all profile"""
    neigh = []
    for p, part in enumerate(state):
        if p==0:
            continue
        # enumerate neighbors for THIS profile
        for nb in profile_part_neighbors_ubs(part, min_len=min_len):
            y_new = state.copy()  # new list object (shallow copy)
            # enforce tuple for cov_ids; deep-copy B to avoid aliasing
            cov_tup = None if nb.cov_ids is None else tuple(nb.cov_ids)
            B_copy  = _copy_B(nb.B)
            y_new[p] = ProfilePart(cov_ids=cov_tup, B=B_copy)

            # skip exact self
            if states_equal(state, y_new):
                continue

            neigh.append(y_new)

    # dedupe neighbors (important if multiple flips lead to same global state)
    seen=set(); uniq=[]
    for s in neigh:
        sig=_state_signature(s)
        if sig in seen: 
            continue
        seen.add(sig)
        uniq.append(s)
    return uniq


Little example of the algorithm finding neighborhood containing four matrices for one sigma

In [36]:
anchor = build_anchor_states(R_set, R_profiles, M, R)

state_neighbors_ubs(anchor[2], min_len=1)[0][1].B

array([[0.]])

In [37]:
anchor[2][1].B

array([[1.]])

In [38]:
states_equal(state_neighbors_ubs(anchor[2], min_len=1)[4],anchor[2])

False

### Define appropriate warm start proposal

In [39]:
# from dataclasses import dataclass

# @dataclass
# class Q0Buckets:
#     eps1: float
#     eps2: float
#     S0_sigs: set
#     S1_sigs: set
#     S1_map: dict           # sig -> concrete State
#     size_S0: int
#     size_S1: int
#     size_Sgt1: int         # |Ω| - |S0| - |S1|

# def total_space_size(example_state, R_per):
#     # product_k 2^{C_k}, where C_k = # finite editable bits in profile k
#     import numpy as np
#     C_per = np.maximum(np.asarray(R_per, int)-2, 0)
#     total = 1
#     for pp in example_state:
#         if pp.cov_ids:
#             active = np.asarray(pp.cov_ids, int)
#             total *= (1 << int(C_per[active==1].sum()))
#     return total

# def make_q0_buckets(RPS, R_per, eps1=0.05, eps2=0.25, min_len=1):
#     S0_sigs = { _state_signature(s) for s in RPS }
#     S1_sigs,set_map = set(), {}
#     for s in RPS:
#         for n in state_neighbors_ubs(s, min_len=min_len):   # enumerate the 1-edit neighborhood and count
#             sig = _state_signature(n)
#             if sig in S0_sigs or sig in S1_sigs: continue
#             S1_sigs.add(sig); set_map[sig] = n
#     size_Omega = total_space_size(RPS[0], R_per)
#     return Q0Buckets(eps1, eps2, S0_sigs, S1_sigs, set_map,
#                      len(S0_sigs), len(S1_sigs),
#                      max(0, size_Omega - len(S0_sigs) - len(S1_sigs)))

# def log_q0_distance(x, buckets: Q0Buckets):
#     sig = _state_signature(x)
#     if sig in buckets.S0_sigs:
#         return math.log(buckets.eps1) - math.log(max(1, buckets.size_S0))
#     if sig in buckets.S1_sigs:
#         return math.log(buckets.eps2 - buckets.eps1) - math.log(max(1, buckets.size_S1))
#     return math.log(1.0 - buckets.eps2) - math.log(max(1, buckets.size_Sgt1))

### Second step: AIS, proposal

In [40]:
# # ---------- q0, MH, AIS on this state space ----------
# def states_equal(a: State, b: State) -> bool:
#     if len(a)!=len(b): return False
#     for ap,bp in zip(a,b):
#         if ap.cov_ids != bp.cov_ids: return False
#         if not np.array_equal(ap.B, bp.B): return False
#     return True

# def Kh_logpdf_state_stay_or_step(x: State, a: State, p_stay=0.25, min_len=1):
#     if states_equal(x,a): return math.log(p_stay)
#     N = state_neighbors_ubs(a, min_len=min_len)
#     for n in N:
#         if states_equal(x,n):
#             return math.log(1.0-p_stay) - math.log(len(N))
#     return float("-inf")

# def Kh_sample_state_stay_or_step(a: State, rng: np.random.Generator, p_stay=0.25, min_len=1):
#     if rng.random() < p_stay:  # stay
#         return [ProfilePart(cov_ids=p.cov_ids, B=(p.B.copy() if p.B is not None else None)) for p in a]
#     N = state_neighbors_ubs(a, min_len=min_len)
#     if not N:
#         return [ProfilePart(cov_ids=p.cov_ids, B=(p.B.copy() if p.B is not None else None)) for p in a]
#     return N[rng.integers(0,len(N))]

# def _make_rps_probs(RPS: List[State], score_s: Callable[[State], float]) -> np.ndarray:
#     w = np.array([max(0.0, float(score_s(A))) for A in RPS], dtype=float)
#     w[~np.isfinite(w)] = 0.0
#     return np.full(len(RPS), 1.0/len(RPS)) if w.sum()<=0 else (w / w.sum())


# from dataclasses import dataclass

# @dataclass
# class AnchorMixture:
#     anchors: List[State]
#     log_alpha: List[float]
#     p_stay: float = 0.25
#     min_len: int = 1
#     def __post_init__(self):
#         m = max(self.log_alpha) if self.log_alpha else 0.0
#         w = [math.exp(z-m) for z in self.log_alpha] or [1.0]
#         Z = sum(w) or 1.0
#         self.alpha = [wi/Z for wi in w]
#     def log_q0(self, x: State) -> float:
#         terms=[]
#         for a,A in zip(self.alpha, self.anchors):
#             if a==0: continue
#             lk = Kh_logpdf_state_stay_or_step(x, A, p_stay=self.p_stay, min_len=self.min_len)
#             if lk==float("-inf"): continue
#             terms.append(math.log(a)+lk)
#         if not terms: return float("-inf")
#         m=max(terms); return m+math.log(sum(math.exp(z-m) for z in terms))
#     def sample_q0(self, rng: np.random.Generator) -> State:
#         idx = rng.choice(len(self.anchors), p=np.array(self.alpha))
#         return Kh_sample_state_stay_or_step(self.anchors[idx], rng, p_stay=self.p_stay, min_len=self.min_len)
    
# # assume you already have: AnchorMixture.log_q0_local(x) and .sample_q0_local(rng)


# def _count_bits_in_B(B) -> Tuple[int, int]:
#     """Return (#ones, #zeros) for a compact B. Treat non-finite as 0."""
#     if B is None:
#         return 0, 0
#     if isinstance(B, np.ndarray):
#         arr = np.asarray(B, float)
#         if arr.ndim == 1:
#             valid = np.isfinite(arr)
#             ones = int((arr[valid] > 0).sum())
#             zeros = int(valid.sum() - ones)
#             return ones, zeros
#         elif arr.ndim == 2:
#             valid = np.isfinite(arr)
#             ones = int((arr[valid] > 0).sum())
#             zeros = int(valid.sum() - ones)
#             return ones, zeros
#         else:
#             raise TypeError("B ndarray must be 1D or 2D")
#     if isinstance(B, (list, tuple)):
#         ones = zeros = 0
#         for row in B:
#             r = np.asarray(row, float).ravel()
#             valid = np.isfinite(r)
#             ones += int((r[valid] > 0).sum())
#             zeros += int(valid.sum() - (r[valid] > 0).sum())
#         return ones, zeros
#     raise TypeError(f"Unsupported B type: {type(B)}")

# def count_bits_compact_state(state: List[ProfilePart]) -> Tuple[int, int]:
#     """Sum (#ones, #zeros) across all profiles in compact form."""
#     ones = zeros = 0
#     for pp in state:
#         o, z = _count_bits_in_B(pp.B)
#         ones += o; zeros += z
#     return ones, zeros

# def log_q_base_compact(state: List[ProfilePart], pi_base: float) -> float:
#     """Independent Bernoulli(pi_base) over every finite entry present in compact B’s."""
#     ones, zeros = count_bits_compact_state(state)
#     if ones == 0 and zeros == 0:
#         # no finite coordinates in the compact state; define as 0 (or return a constant)
#         return 0.0
#     return ones * math.log(pi_base) + zeros * math.log(1.0 - pi_base)

# class AnchorMixtureWithBaseCompact:
#     def __init__(self, local_mixture, epsilon=1e-3, pi_base=0.5, base_move="stay"):
#         """
#         local_mixture: your existing AnchorMixture(anchors, log_alpha, p_stay, min_len)
#         epsilon: weight on the base component (full support). set to 0.0 to disable.
#         pi_base: Bernoulli prob for base log-density (only used in log_q0).
#         base_move: "stay" or "stay_or_step" (how to sample when taking the base branch)
#         """
#         self.local = local_mixture          # your existing AnchorMixture (already loss-weighted via alpha)
#         self.epsilon = float(epsilon)
#         self.pi_base = float(pi_base)       # kept for compatibility; unused in this base sampler
#         assert base_move in ("stay", "stay_or_step")
#         self.base_move = base_move

#     def log_q0(self, x_state):
#         # unchanged: mixture of local q0 and simple compact-base (if you still use it)
#         lq_local = self.local.log_q0(x_state)
#         # if you want to drop the “compact Bernoulli base” entirely, set epsilon=0
#         lq_base  = log_q_base_compact(x_state, self.pi_base)
#         t1 = math.log1p(-self.epsilon) + lq_local
#         t2 = math.log(self.epsilon)     + lq_base
#         m = max(t1, t2)
#         return m + math.log(math.exp(t1 - m) + math.exp(t2 - m))

#     def sample_q0(self, rng):
#         if rng.random() >= 0:
#             # local: same as before (already loss-weighted across anchors via self.local.alpha)
#             return self.local.sample_q0(rng)

#         # ----- BASE BRANCH (loss-weighted over anchors; no random fabrication) -----
#         # pick an anchor index according to alpha (alpha ∝ exp(log_alpha) ∝ loss-weighted score)
#         idx = rng.choice(len(self.local.anchors), p=np.array(self.local.alpha))
#         A = self.local.anchors[idx]

#         if self.base_move == "stay":
#             # return a deep copy of the chosen anchor (no random edit)
#             return [ProfilePart(cov_ids=p.cov_ids,
#                                 B=(p.B.copy() if p.B is not None else None)) for p in A]

#         # optional: do your UBS “stay-or-step” move from the chosen anchor
#         return Kh_sample_state_stay_or_step(
#             A, rng, p_stay=self.local.p_stay, min_len=self.local.min_len
#         )


### Integrate the helper functions to do the AIS procedure

In [ ]:
# def make_ladder(K:int, gamma:float=4.0):
#     if K<2: return np.array([1.0], float)
#     g=np.linspace(0.0,1.0,K); return g**gamma

# @dataclass
# class AISConfig:
#     n_paths:int=600
#     n_levels:int=40
#     moves_per_level:int=12
#     min_len:int=1
#     seed:Optional[int]=2

# @dataclass
# class AISOutput:
#     terminals: List[State]
#     logw: np.ndarray
#     normw: np.ndarray
#     ladder: np.ndarray

# def mh_step_state_uniform_neighbors(x: State, t: float, log_q0, score_s, min_len=1) -> State:
#     N_cur = state_neighbors_ubs(x, min_len=min_len)
#     if not N_cur: return x
#     prop = random.choice(N_cur) # random proposal from the neighbourhood
#     N_prop = state_neighbors_ubs(prop, min_len=min_len) # neighbourhood of the proposed state
#     def logpi_t(z: State): # target distribution at this specifc t
#         lq0 = log_q0(z)
#         if lq0==float("-inf"): return float("-inf")
#         return (1.0-t)*lq0 + t*np.log(score_s(z)) # formula for target dist at ladder step t
#     lcur, lprop = logpi_t(x), logpi_t(prop) # pi_t of x and proposed 
#     if lprop == float("-inf"): return x
#     logr = (lprop-lcur) + math.log(max(1,len(N_cur))) - math.log(max(1,len(N_prop))) # acceptance ratio
#     if math.log(random.random()+1e-300) < min(0.0, logr): return prop
#     return x

# def run_ais_state(anchors: List[State], score_s: Callable[[State], float], cfg: AISConfig=AISConfig()) -> AISOutput:
#     if cfg.seed is not None:
#         np.random.seed(cfg.seed); random.seed(cfg.seed)
#     rng = np.random.default_rng(cfg.seed)
#     log_alpha = [score_s(A) for A in anchors]
#     local_mix = AnchorMixture(anchors, log_alpha, p_stay=0.0005, min_len=cfg.min_len)
#     mix = AnchorMixtureWithBaseCompact(local_mix, epsilon=1e-3, pi_base=0.5, base_move="stay_or_step")
#     ladder = make_ladder(cfg.n_levels)
#     terminals=[]
#     logw=np.zeros(cfg.n_paths,float)
#     for p in range(cfg.n_paths):
#         x = mix.sample_q0(rng); lw=0.0 # start with initial sample from anchor and one MH step
#         for t_prev, t_cur in zip(ladder[:-1], ladder[1:]):
#             lq0_x = mix.log_q0(x); s_x = score_s(x) # calculate relevant posterior for specific x
#             if lq0_x==float("-inf"):
#                 x=mix.sample_q0(rng); lq0_x=mix.log_q0(x); s_x=score_s(x)
#             lw += (t_cur - t_prev) * (np.log(s_x) - lq0_x)
#             print(np.log(s_x))
#             print(lq0_x)
#             for _ in range(cfg.moves_per_level):
#                 x = mh_step_state_uniform_neighbors(x, t_cur, mix.log_q0, score_s, min_len=cfg.min_len)
#         terminals.append([ProfilePart(cov_ids=pp.cov_ids, B=(pp.B.copy() if pp.B is not None else None)) for pp in x])
#         logw[p]=lw
#     m=float(np.max(logw)); w=np.exp(logw-m); return AISOutput(terminals, logw, w/w.sum(), ladder)


### Updated code for warm start p0 (written as q0)

In [42]:
import math, random, numpy as np
from dataclasses import dataclass
from typing import List, Callable, Optional, Tuple, Set, Dict

# assume: ProfilePart, profile_part_neighbors_ubs, state_neighbors_ubs, states_equal already exist
State = List["ProfilePart"]

# ---------- helpers to make minimal changes ----------
def _softmax_logalpha(log_alpha: List[float], tau: float = 1.0) -> np.ndarray:
    z = np.array(log_alpha, float) / max(1e-12, tau)
    m = float(np.max(z))
    w = np.exp(z - m)
    s = w.sum()
    return w / s if s > 0 else np.full_like(w, 1.0 / len(w))

def _copy_state(x: State) -> State:
    out=[]
    for pp in x:
        cov = None if pp.cov_ids is None else tuple(pp.cov_ids)
        if pp.B is None: Bc=None
        else:
            arr = np.asarray(pp.B)
            Bc = arr.copy() if isinstance(pp.B, np.ndarray) else [np.asarray(r).copy() for r in pp.B]
        out.append(type(pp)(cov_ids=cov, B=Bc))
    return out

def state_signature(s: State) -> Tuple:
    sig=[]
    for pp in s:
        cov = None if pp.cov_ids is None else tuple(pp.cov_ids)
        if pp.B is None: Bsig=('None',)
        else:
            A = np.asarray(pp.B, float)
            Bsig=(A.shape, tuple(A.ravel()))
        sig.append((cov, Bsig))
    return tuple(sig)

def _count_profile_bits(pp, R_per: np.ndarray) -> int: # for each profile, how many non-inf elements in the sigma matrices
    if pp.cov_ids is None: return 0
    cov = np.asarray(pp.cov_ids, int)
    C_per = np.maximum(np.asarray(R_per, int) - 2, 0) #length of P, each element representing # of the possible boundary for one feature
    return int(C_per[cov==1].sum()) # sum of possible boundary slot across all active features

def _total_space_size(example_state: State, R_per: np.ndarray) -> int: # for the whole space, how many possible partitions (distinct sigma matrices)
    tot = 1
    for pp in example_state:
        Ck = _count_profile_bits(pp, R_per)
        tot *= (1 << Ck) # raise to the power of 2
    return tot # sum of possible partitions within each profile

@dataclass
class Q0BucketsWeightedS0:
    eps1: float
    eps2: float
    S0_sigs: Set[Tuple]
    S1_sigs: Set[Tuple]
    S1_map: Dict[Tuple, State]          # optional: sig -> concrete neighbor (used if sampling S1)
    size_S1: int
    size_Sgt1: int
    S0_logprob: Dict[Tuple, float]      # NEW: per-RPS state log prob ∝ exp(log_alpha)

# count the size of 1-edit, whole model space, to get prob for warm start proposal
def make_q0_buckets_weighted_S0(RPS: List[State],
                                R_per: np.ndarray,
                                log_alpha: List[float],
                                eps1: float = 0.05,
                                eps2: float = 0.25,
                                min_len: int = 1) -> Q0BucketsWeightedS0:
    # S0: RPS signatures
    S0_sigs = [state_signature(s) for s in RPS]
    # normalize weights inside S0 using your existing log_alpha
    p_rps = _softmax_logalpha(log_alpha)                            # CHANGED: reuse log_alpha
    S0_logprob = {sig: math.log(p_rps[i]) for i, sig in enumerate(S0_sigs)}

    # S1: union of 1-edit neighbors (unique), excluding S0
    S0_set = set(S0_sigs)
    S1_sigs: Set[Tuple] = set()
    S1_map: Dict[Tuple, State] = {}
    for s in RPS:
        for n in state_neighbors_ubs(s, min_len=min_len):
            sig = state_signature(n)
            if sig in S0_set or sig in S1_sigs: continue
            S1_sigs.add(sig); S1_map[sig] = n

    size_Omega = _total_space_size(RPS[0], np.asarray(R_per, int))
    size_S1 = len(S1_sigs)
    size_Sgt1 = max(0, size_Omega - len(S0_sigs) - size_S1)

    return Q0BucketsWeightedS0(
        eps1=eps1, eps2=eps2,
        S0_sigs=set(S0_sigs),
        S1_sigs=S1_sigs, S1_map=S1_map,
        size_S1=size_S1, size_Sgt1=size_Sgt1,
        S0_logprob=S0_logprob
    )

def log_q0_distance_weighted_S0(x: State, buckets: Q0BucketsWeightedS0) -> float:
    sig = state_signature(x)
    if sig in buckets.S0_sigs: # sum of prob for all states within RPS equals eps1
        # mass eps1 distributed by alpha within S0  (not uniform)
        return math.log(buckets.eps1) + buckets.S0_logprob[sig]      # CHANGED: weighted by log_alpha
    if sig in buckets.S1_sigs: # sum of prob for all states within 1-edit neighborhood equals eps2-eps1
        if buckets.size_S1 == 0: return float("-inf")
        return math.log(buckets.eps2 - buckets.eps1) - math.log(buckets.size_S1)
    if buckets.size_Sgt1 == 0: return float("-inf") # sum of prob for all other states equals 1-eps2
    return math.log(1.0 - buckets.eps2) - math.log(buckets.size_Sgt1)

# ---------- AIS driver: ONLY two tiny changes (init & q0), both use log_alpha ----------
@dataclass
class AISConfig:
    n_paths:int=600; n_levels:int=40; moves_per_level:int=12; min_len:int=1; seed:Optional[int]=2

@dataclass
class AISOutput:
    terminals: List[State]; logw: np.ndarray; normw: np.ndarray; ladder: np.ndarray

def make_ladder(K:int, gamma:float=4.0) -> np.ndarray:
    if K<2: return np.array([0.0,1.0], float)
    g=np.linspace(0,1,K); return g**gamma # if gamma > 0, the ladder is denser near 0 and sparser near 1

def mh_step_state_uniform_neighbors(x: State, t: float,
                                    log_q0: Callable[[State], float],
                                    score_s: Callable[[State], float],
                                    min_len:int=1) -> State:
    """One step of MH used in proposal"""
    N_cur = [n for n in state_neighbors_ubs(x, min_len=min_len) if not states_equal(n, x)]
    if not N_cur: return x
    prop = random.choice(N_cur)
    N_prop = [n for n in state_neighbors_ubs(prop, min_len=min_len) if not states_equal(n, prop)]
    def logpi_t(z: State) -> float:
        lq = log_q0(z)
        if lq==float("-inf"): return float("-inf")
        return (1.0 - t)*lq + t*math.log(max(1e-300, score_s(z))) # target dist determined by t
    lcur, lprop = logpi_t(x), logpi_t(prop)
    if lprop == float("-inf"): return x
    logr = (lprop-lcur) + math.log(max(1,len(N_cur))) - math.log(max(1,len(N_prop))) # matropolis hasting
    if math.log(random.random()+1e-300) < min(0.0, logr): return prop
    return x

def run_ais_state(anchors: List[State],
                  score_s: Callable[[State], float],
                  cfg: AISConfig = AISConfig(),
                  RPS: Optional[List[State]] = None,
                  R_per: Optional[np.ndarray] = None,
                  eps1: float = 0.05, eps2: float = 0.25,
                  tau_init: float = 1.0) -> AISOutput:
    if cfg.seed is not None:
        np.random.seed(cfg.seed); random.seed(cfg.seed)
    rng = np.random.default_rng(cfg.seed)

    # already compute this earlier in the code:
    log_alpha = [score_s(A) for A in anchors]                       # existing line in your code

    # NEW q0 built from RPS using existing log_alpha (weighted S0)
    if RPS is None or R_per is None:
        raise ValueError("Provide RPS and R_per for the distance-bucket q0.")
    buckets = make_q0_buckets_weighted_S0(RPS, np.asarray(R_per,int), log_alpha, eps1=eps1, eps2=eps2, min_len=cfg.min_len)
    log_q0 = lambda z: log_q0_distance_weighted_S0(z, buckets)      # CHANGED: new q0

    ladder = make_ladder(cfg.n_levels)

    # INIT: sample ONLY from RPS, using softmax(log_alpha)        (minimal change)
    p_rps = _softmax_logalpha(log_alpha, tau=tau_init)               # CHANGED: reuse log_alpha
    # --------------------------------------------------------------------------

    terminals=[]; logw=np.zeros(cfg.n_paths,float)
    for p in range(cfg.n_paths):
        # initial x from RPS by loss weights
        idx0 = rng.choice(len(RPS), p=p_rps)                         # CHANGED
        x = _copy_state(RPS[idx0])                                   # CHANGED
        lw = 0.0                                                     # keep simple; add init-correction if you want

        beta_prev = ladder[0]
        for beta_cur in ladder[1:]:
            # AIS weight increment
            lq = log_q0(x)
            lp = math.log(max(1e-300, score_s(x)))
            lw += (beta_cur - beta_prev) * (lp - lq) # move to next ladder, update weight
            print(lp)
            print(lq)
            # MH moves at level beta_cur
            for _ in range(cfg.moves_per_level):
                x = mh_step_state_uniform_neighbors(x, beta_cur, log_q0, score_s, min_len=cfg.min_len)
                # proposal step, moves_per_level steps of MH movements
            beta_prev = beta_cur

        terminals.append(_copy_state(x))
        logw[p]=lw

    m=float(np.max(logw)); w=np.exp(logw-m)
    return AISOutput(terminals, logw, w/w.sum(), ladder)


### Code to compute true posterior (via computing loss for each global partition)

In [43]:
import numpy as np
from typing import Any, Sequence, Optional, Union
from rashomon.loss import compute_Q as _compute_Q

# ---------- 1) Q when sigma is None: one-pool predictor (mean of y_k) ----------
def _compute_Q_none_mean(D_k: np.ndarray, y_k: np.ndarray, *, reg: float, normalize: int) -> float:
    yv = y_k.ravel()
    if yv.size:
        mu = float(np.mean(yv))
        mse = float(np.mean((yv - mu) ** 2))
        if normalize:
            mse = mse * yv.size / float(normalize)
    else:
        mse = 0.0
    h = 1  # one pool
    return mse + reg * h

# ---------- 2) Global loss: sum per-profile losses; DO NOT touch non-None sigma ----------
RLike = Union[int, Sequence[int], np.ndarray]

## to use compute_Q, need to full (M × C) sigma with C = max(R_m - 2)
def assemble_sigma_full_for_profile(
    part,
    M: int,                            # number of features/arms
    R: Sequence[int],                  # per-arm levels, length M
) -> np.ndarray:
    """
    Build a full (M × C) sigma with C = max(R_m - 2).
    For arm m, only the first (R_m - 2) entries are meaningful; the rest are +inf.
    Active arms (cov_ids[m] == 1) get their row from B (padded/truncated as needed).
    Inactive arms get +inf.
    """
    if part is None:
        return None
    
    B = getattr(part, "B", None)
    cov_ids = getattr(part, "cov_ids", None)

    R = np.asarray(R, dtype=int)
    assert R.shape[0] == M, "R must be length M"
    # internal boundary count per arm
    C_per = np.maximum(R - 2, 0)
    C = int(C_per.max()) if M > 0 else 0

    # full matrix filled with +inf (inactive/no-boundary sentinel)
    Sigma = np.full((M, C), np.inf, dtype=float)

    # handle trivial cases
    if C == 0:
        return Sigma  # nothing to place; all rows are effectively inactive

    # binary mask of actives
    if cov_ids is None:
        active_mask = np.zeros(M, dtype=int)
    else:
        active_mask = np.asarray(cov_ids, dtype=int).reshape(-1)
        if active_mask.size != M:
            raise ValueError("cov_ids must be a binary mask of length M")

    active_idx = np.nonzero(active_mask)[0]
    A = active_idx.size
    if A == 0 or B is None:
        return Sigma  # all inactive or no B provided

    # normalize B to a list of row arrays, one per active arm (in ascending arm index)
    rows = []

    # Case 1: 1D → only one active arm
    if isinstance(B, np.ndarray) and B.ndim == 1:
        if A != 1:
            raise ValueError("B is 1D but multiple active arms in cov_ids")
        rows = [np.asarray(B, dtype=float)]

    # Case 2: 2D → rows correspond to active arms in the order of active_idx
    elif isinstance(B, np.ndarray) and B.ndim == 2:
        if B.shape[0] != A:
            raise ValueError(f"B has {B.shape[0]} rows; expected {A} (number of active arms)")
        rows = [np.asarray(B[r], dtype=float) for r in range(A)]

    # Case 3: ragged list/tuple of rows
    elif isinstance(B, (list, tuple)):
        if len(B) != A:
            raise ValueError(f"len(B)={len(B)}; expected {A} (number of active arms)")
        rows = [np.asarray(row, dtype=float) for row in B]

    else:
        raise TypeError(f"Unsupported B type: {type(B)}")

    # place each active row into its arm with correct per-arm width
    for row_arr, m in zip(rows, active_idx):
        need = int(C_per[m])            # columns that are meaningful for arm m
        if need == 0:
            continue                    # arm has no internal boundary positions
        # trim/pad the source row to 'need', then place into Sigma[m, :need]
        src = row_arr.ravel()
        if src.size < need:
            src = np.pad(src, (0, need - src.size), mode="constant", constant_values=0.0)
        elif src.size > need:
            src = src[:need]
        Sigma[m, :need] = src

    return Sigma

def _compute_Q_none_mean(y_k, *, reg: float, normalize: int) -> float:
    yv = np.asarray(y_k).ravel()
    if yv.size:
        mu = float(np.mean(yv))
        mse = float(np.mean((yv - mu) ** 2))
        if normalize:
            mse = mse * yv.size / float(normalize)
    else:
        mse = 0.0
    return mse + reg * 1  # one pool

def build_profile_index_of_policy(policies, policy_to_profile):
    profs = [policy_to_profile(p) for p in policies]
    uniq = sorted(set(profs))
    prof_to_idx = {pr: i for i, pr in enumerate(uniq)}
    prof_idx = np.array([prof_to_idx[pr] for pr in profs], dtype=int)
    return prof_idx, uniq

def global_loss_raw(
    state,                      # list[ProfilePart or raw sigma/None], length = num_profiles
    D, y,                       # D: (N,1) global policy ids; y: (N,) or (N,1)
    policies,                   # list of ALL policies (len = num_policies)
    policy_means,               # (num_policies, 2)
    prof_idx_of_policy,         # np.ndarray(len=num_policies): profile index for each policy
    M: int,                     # number of features/arms in this profile family
    R,
    reg: float = 1.0,
    normalize: int = 0,
    lattice_edges=None,
) -> float:
    """Compute the loss for one global partition"""
    # coerce arrays
    D_arr = np.asarray(D);  y_arr = np.asarray(y)
    if D_arr.ndim == 1: D_arr = D_arr.reshape(-1, 1)
    if y_arr.ndim == 1: y_arr = y_arr.reshape(-1, 1)

    total = 0.0
    num_profiles = len(state)
    num_policies = len(policies)

    # which policy ids belong to each profile?
    pol_ids_by_profile = [np.where(prof_idx_of_policy == k)[0] for k in range(num_profiles)]
    pid_global = D_arr[:, 0].astype(int)

    for k in range(num_profiles):
        part_k = state[k]
        pol_ids = pol_ids_by_profile[k]
        if pol_ids.size == 0:
            total += _compute_Q_none_mean([], reg=reg, normalize=normalize)
            continue

        mask = np.isin(pid_global, pol_ids)
        if not np.any(mask):
            total += _compute_Q_none_mean([], reg=reg, normalize=normalize)
            continue

        D_k = D_arr[mask].copy()
        y_k = y_arr[mask].copy()

        # remap policy ids in D_k to local 0..(P_k-1)
        local_map = -np.ones(num_policies, dtype=int)
        local_map[pol_ids] = np.arange(pol_ids.size, dtype=int)
        D_k[:, 0] = local_map[D_k[:, 0].astype(int)]

        policies_k = [policies[i] for i in pol_ids]
        pm_k = np.asarray(policy_means)[pol_ids, :]

        # Expand per-profile candidate to full M rows for compute_Q
        Sigma_k_full = assemble_sigma_full_for_profile(part_k, M, R)

        if Sigma_k_full is None:
            Q_k = _compute_Q_none_mean(y_k, reg=reg, normalize=normalize)
        else:
            Q_k = float(_compute_Q(
                D=D_k, y=y_k, sigma=Sigma_k_full,
                policies=policies_k, policy_means=pm_k,
                reg=reg, normalize=normalize, lattice_edges=lattice_edges
            ))
        total += Q_k

    return total


# ---------- 3) AIS score: exp(-beta * global_loss_raw(state)) ----------
def make_score_s_expneg_raw(
    *,
    D,
    y,
    M,
    R,
    prof_idx_of_policy,
    policies,
    policy_means,
    reg: float = 1.0,
    normalize: int = 0,
    lattice_edges=None,
    beta: float = 1.0,                 # set 1.0 for exp(-loss)
    prior_logprob=lambda state: 0.0,   # optional log-prior
):
    """Return score = exp(-loss)"""
    def score_s(state):
        Q = global_loss_raw(
            state=state,
            D=D, y=y, M=M, R=R,
            prof_idx_of_policy = prof_idx_of_policy,
            policies=policies,
            policy_means=policy_means,
            reg=reg, normalize=normalize,
            lattice_edges=lattice_edges,
        )
        return float(np.exp(prior_logprob(state) - beta * Q))
    return score_s


### Helper function to convert output of RAggregate to ideal format

In [44]:
import numpy as np
from typing import List, Tuple

# The output from RAggregate is R_set and R_profile, convert to the list of states (each state a list of profiles) as we defined

State = List["ProfilePart"]

def _as_compact_B(sigma):
    """Normalize per-profile sigma from RAggregate into B (or None)."""
    if sigma is None:
        return None
    A = np.asarray(sigma)
    # Some profiles return a single column of +inf when R=2 (no interior cuts).
    # Treat any-all-inf row/array as 'no editable bits' -> None.
    if np.isinf(A).all():
        return None
    return A

def raggregate_to_states(
    RPS_output,
    profiles: List[Tuple[int, ...]],   # cov_ids per profile (binary tuple of length M)
) -> List[State]:
    """
    Convert RAggregate output into a list[State].
    - RPS_output can be a tuple (R_set, R_profiles) from RAggregate,
      or just R_set if you've already dereferenced sigmas.
    - profiles: list of binary tuples (cov_ids) aligned with per-profile Rashomon sets.
    """
    # Unpack
    if isinstance(RPS_output, tuple) and len(RPS_output) == 2:
        R_set, R_profiles = RPS_output
        # R_profiles is a list (one entry per profile), where each entry
        # holds a collection (list/array) of candidate sigma matrices for that profile.
        def get_sigma(profile_idx: int, idx_in_profile: int):
            rp = R_profiles[profile_idx]
            # RashomonSet object or plain list
            if hasattr(rp, "sigma"):
                return rp.sigma[idx_in_profile]
            return rp[idx_in_profile]
    else:
        # If caller already resolved to matrices per profile, assume R_set has concrete sigmas.
        R_set = RPS_output
        R_profiles = None
        def get_sigma(profile_idx: int, idx_in_profile: int):
            # Here R_set[i][k] is expected to be the actual sigma for profile k
            return idx_in_profile  # pass-through

    states: List[State] = []
    n_profiles = len(profiles)

    for g in R_set:
        # Each g is a list of indices, one per profile: g[k] indexes the chosen sigma for profile k
        if len(g) != n_profiles:
            raise ValueError(f"Global choice length {len(g)} != number of profiles {n_profiles}")
        state: State = []
        for k, choice in enumerate(g):
            cov_ids = tuple(profiles[k]) if profiles[k] is not None else None
            sigma_k = get_sigma(k, choice)
            B_k = _as_compact_B(sigma_k)
            state.append(ProfilePart(cov_ids=cov_ids, B=B_k))
        states.append(state)

    return states


### Finally the AIS sample step

In [46]:
# anchors: list[ProfilePart] per profile (your state format)
anchors = build_anchor_states(R_set, R_profiles, M, R)
prof_idx_of_policy, profiles = build_profile_index_of_policy(all_policies, hasse.policy_to_profile)

RPS_states = raggregate_to_states((R_set, R_profiles), profiles)

# build the scorer for AIS
score_s = make_score_s_expneg_raw(
    D=D,
    y=y,
    M=M,
    R=R,
    prof_idx_of_policy = prof_idx_of_policy,
    policies=all_policies,
    policy_means=policy_means,
    reg=lamb,
    lattice_edges=None,   # or your edges
    beta=1.0,             # exp(-loss)
    prior_logprob=lambda state: 0.0
)

# then pass score_s into your AIS routine
# ais_out = run_ais_state(anchors, score_s=score_s, cfg=cfg)
cfg = AISConfig(n_paths=5, n_levels=5, moves_per_level=5, min_len=1, seed=2)
# out = run_ais_state(
#     anchors=RPS_states,          # not used by q0, but you may keep for consistency
#     score_s=score_s,        # returns exp(-loss(state)) or similar
#     cfg=cfg,
#     RPS=RPS_states,              # your Rashomon partitions as a list of State
#     R_per=R,  # levels per arm (includes control)
#     eps1=0.05, eps2=0.25
# )


# cfg = AISConfig(n_paths=2, n_levels=10, moves_per_level=12, min_len=1, seed=3)
# ais_out = run_ais_state(anchors, score_s=score_s, cfg=cfg)


In [ ]:
out.logw

array([-23.65888357, -22.48200332, -21.4611147 , -19.48180522,
       -21.61737274])

In [ ]:
import pickle
import gzip

def save_ais_pickle(path: str, particles: List[List[ProfilePart]], weights, meta: dict | None = None):
    """
    path: e.g. 'ais_run.pkl' or 'ais_run.pkl.gz' (gzip if endswith .gz)
    particles: list of states; each state = list[ProfilePart]
    weights: array-like of floats (same length as particles)
    meta: optional dict with run info (seed, ladder, etc.)
    """
    payload = {
        "particles": particles,
        "weights": np.asarray(weights, float),
        "meta": meta or {}
    }
    opener = gzip.open if path.endswith(".gz") else open
    with opener(path, "wb") as f:
        # Use highest protocol for speed/size
        pickle.dump(payload, f, protocol=pickle.HIGHEST_PROTOCOL)

def load_ais_pickle(path: str):
    """Returns (particles, weights, meta)."""
    opener = gzip.open if path.endswith(".gz") else open
    with opener(path, "rb") as f:
        obj = pickle.load(f)
    return obj["particles"], obj["weights"], obj.get("meta", {})

In [ ]:
# save_ais_pickle("ais_particles.pkl.gz", ais_out.terminals, ais_out.normw,
#                 meta={"run_id":"first_trial","n_paths":600,"n_levels":40,"moves_per_level":12,"reg":1,"seed":3,"min_length":1})

# particles2, weights2, meta2 = load_ais_pickle("ais_particles.pkl.gz")


In [ ]:
# import numpy as np
# from rashomon.loss import compute_Q as _compute_Q

# # Expand a per-profile candidate to full M rows so compute_Q can index sigma[arm, ...].
# import numpy as np
# from typing import Optional, Sequence, Any

# def assemble_sigma_full_for_profile(
#     part,
#     M: int,                            # number of features/arms
#     R: Sequence[int],                  # per-arm levels, length M
# ) -> np.ndarray:
#     """
#     Build a full (M × C) sigma with C = max(R_m - 2).
#     For arm m, only the first (R_m - 2) entries are meaningful; the rest are +inf.
#     Active arms (cov_ids[m] == 1) get their row from B (padded/truncated as needed).
#     Inactive arms get +inf.
#     """
#     if part is None:
#         return None
    
#     B = getattr(part, "B", None)
#     cov_ids = getattr(part, "cov_ids", None)

#     R = np.asarray(R, dtype=int)
#     assert R.shape[0] == M, "R must be length M"
#     # internal boundary count per arm
#     C_per = np.maximum(R - 2, 0)
#     C = int(C_per.max()) if M > 0 else 0

#     # full matrix filled with +inf (inactive/no-boundary sentinel)
#     Sigma = np.full((M, C), np.inf, dtype=float)

#     # handle trivial cases
#     if C == 0:
#         return Sigma  # nothing to place; all rows are effectively inactive

#     # binary mask of actives
#     if cov_ids is None:
#         active_mask = np.zeros(M, dtype=int)
#     else:
#         active_mask = np.asarray(cov_ids, dtype=int).reshape(-1)
#         if active_mask.size != M:
#             raise ValueError("cov_ids must be a binary mask of length M")

#     active_idx = np.nonzero(active_mask)[0]
#     A = active_idx.size
#     if A == 0 or B is None:
#         return Sigma  # all inactive or no B provided

#     # normalize B to a list of row arrays, one per active arm (in ascending arm index)
#     rows = []

#     # Case 1: 1D → only one active arm
#     if isinstance(B, np.ndarray) and B.ndim == 1:
#         if A != 1:
#             raise ValueError("B is 1D but multiple active arms in cov_ids")
#         rows = [np.asarray(B, dtype=float)]

#     # Case 2: 2D → rows correspond to active arms in the order of active_idx
#     elif isinstance(B, np.ndarray) and B.ndim == 2:
#         if B.shape[0] != A:
#             raise ValueError(f"B has {B.shape[0]} rows; expected {A} (number of active arms)")
#         rows = [np.asarray(B[r], dtype=float) for r in range(A)]

#     # Case 3: ragged list/tuple of rows
#     elif isinstance(B, (list, tuple)):
#         if len(B) != A:
#             raise ValueError(f"len(B)={len(B)}; expected {A} (number of active arms)")
#         rows = [np.asarray(row, dtype=float) for row in B]

#     else:
#         raise TypeError(f"Unsupported B type: {type(B)}")

#     # place each active row into its arm with correct per-arm width
#     for row_arr, m in zip(rows, active_idx):
#         need = int(C_per[m])            # columns that are meaningful for arm m
#         if need == 0:
#             continue                    # arm has no internal boundary positions
#         # trim/pad the source row to 'need', then place into Sigma[m, :need]
#         src = row_arr.ravel()
#         if src.size < need:
#             src = np.pad(src, (0, need - src.size), mode="constant", constant_values=0.0)
#         elif src.size > need:
#             src = src[:need]
#         Sigma[m, :need] = src

#     return Sigma

# def _compute_Q_none_mean(y_k, *, reg: float, normalize: int) -> float:
#     yv = np.asarray(y_k).ravel()
#     if yv.size:
#         mu = float(np.mean(yv))
#         mse = float(np.mean((yv - mu) ** 2))
#         if normalize:
#             mse = mse * yv.size / float(normalize)
#     else:
#         mse = 0.0
#     return mse + reg * 1  # one pool

# def build_profile_index_of_policy(policies, policy_to_profile):
#     profs = [policy_to_profile(p) for p in policies]
#     uniq = sorted(set(profs))
#     prof_to_idx = {pr: i for i, pr in enumerate(uniq)}
#     prof_idx = np.array([prof_to_idx[pr] for pr in profs], dtype=int)
#     return prof_idx, uniq

# def global_loss_raw(
#     state,                      # list[ProfilePart or raw sigma/None], length = num_profiles
#     D, y,                       # D: (N,1) global policy ids; y: (N,) or (N,1)
#     policies,                   # list of ALL policies (len = num_policies)
#     policy_means,               # (num_policies, 2)
#     prof_idx_of_policy,         # np.ndarray(len=num_policies): profile index for each policy
#     M: int,                     # number of features/arms in this profile family
#     R,
#     reg: float = 1.0,
#     normalize: int = 0,
#     lattice_edges=None,
# ) -> float:
#     # coerce arrays
#     D_arr = np.asarray(D);  y_arr = np.asarray(y)
#     if D_arr.ndim == 1: D_arr = D_arr.reshape(-1, 1)
#     if y_arr.ndim == 1: y_arr = y_arr.reshape(-1, 1)

#     total = 0.0
#     num_profiles = len(state)
#     num_policies = len(policies)

#     # which policy ids belong to each profile?
#     pol_ids_by_profile = [np.where(prof_idx_of_policy == k)[0] for k in range(num_profiles)]
#     pid_global = D_arr[:, 0].astype(int)

#     for k in range(num_profiles):
#         part_k = state[k]
#         pol_ids = pol_ids_by_profile[k]
#         if pol_ids.size == 0:
#             total += _compute_Q_none_mean([], reg=reg, normalize=normalize)
#             continue

#         mask = np.isin(pid_global, pol_ids)
#         if not np.any(mask):
#             total += _compute_Q_none_mean([], reg=reg, normalize=normalize)
#             continue

#         D_k = D_arr[mask].copy()
#         y_k = y_arr[mask].copy()

#         # remap policy ids in D_k to local 0..(P_k-1)
#         local_map = -np.ones(num_policies, dtype=int)
#         local_map[pol_ids] = np.arange(pol_ids.size, dtype=int)
#         D_k[:, 0] = local_map[D_k[:, 0].astype(int)]

#         policies_k = [policies[i] for i in pol_ids]
#         pm_k = np.asarray(policy_means)[pol_ids, :]

#         # Expand per-profile candidate to full M rows for compute_Q
#         Sigma_k_full = assemble_sigma_full_for_profile(part_k, M, R)

#         if Sigma_k_full is None:
#             Q_k = _compute_Q_none_mean(y_k, reg=reg, normalize=normalize)
#         else:
#             Q_k = float(_compute_Q(
#                 D=D_k, y=y_k, sigma=Sigma_k_full,
#                 policies=policies_k, policy_means=pm_k,
#                 reg=reg, normalize=normalize, lattice_edges=lattice_edges
#             ))
#         total += Q_k

#     return total


### Assuming we have the AIS result, how do we get estimation of Betas and model distribution, and how do this compare with the truth?

In [ ]:
policy_means

array([[-1.51211881e+02,  5.00000000e+04],
       [-1.00080186e+05,  5.00000000e+04],
       [-1.00110916e+05,  5.00000000e+04],
       [ 4.99578479e+04,  5.00000000e+04],
       [ 5.00404032e+04,  5.00000000e+04],
       [-9.95893626e+04,  5.00000000e+04],
       [ 4.99370963e+04,  5.00000000e+04],
       [ 5.03976241e+04,  5.00000000e+04],
       [-9.98421239e+04,  5.00000000e+04],
       [-2.81130774e+01,  5.00000000e+04],
       [ 2.12480870e+02,  5.00000000e+04],
       [ 9.98547942e+04,  5.00000000e+04],
       [ 4.56685463e+01,  5.00000000e+04],
       [-4.63057141e+01,  5.00000000e+04],
       [ 9.99388885e+04,  5.00000000e+04],
       [ 5.40863747e+01,  5.00000000e+04],
       [-3.16369845e+01,  5.00000000e+04],
       [ 9.95674113e+04,  5.00000000e+04],
       [ 1.00174522e+05,  5.00000000e+04],
       [ 5.04416610e+04,  5.00000000e+04],
       [-9.97858064e+04,  5.00000000e+04],
       [-1.00030524e+05,  5.00000000e+04],
       [ 2.00032821e+05,  5.00000000e+04],
       [-1.

In [47]:
import numpy as np
from collections import defaultdict

# ---------- 1) posterior-weighted prediction per policy from AIS terminals ----------

def estimate_policy_means_from_ais(
    ais_out,                        # AISOutput: terminals (list[State]), normw (np.ndarray)
    all_policies,                   # list of all policy ids / feature combinations
    policy_means,                   # np.ndarray [P,2] == [sum_y, count] per global policy
    R_per,
    M,
    prof_idx_of_policy,             # np.ndarray or list of length P; maps policy_id -> profile_k
    lattice_edges=None,             # optional lattice for extract_pools (pass None if unused)
):
    """
    Returns: np.ndarray [P] of posterior-weighted mean outcome per policy.
    """
    P = len(all_policies)
    mu_hat = np.zeros(P, dtype=float)

    # Build per-profile index lists (global indices of policies belonging to each profile)
    K = int(np.max(prof_idx_of_policy)) + 1 # number of profiles
    prof_to_global = [ [] for _ in range(K) ]
    for pid in range(P):
        prof_to_global[prof_idx_of_policy[pid]].append(pid) # ith entry contains the list of policies in ith profile

    # For speed: precompute per-profile slices of (policies, policy_means)
    prof_policies   = [ [all_policies[i] for i in idxs] for idxs in prof_to_global ] # from policies index to tuple e.g. (0,0,1)
    prof_means_arr  = [ policy_means[np.array(idxs, int), :] if len(idxs)>0 else np.zeros((0,2))
                        for idxs in prof_to_global ]

    # Accumulate weighted predictions over AIS terminals
    for x_state, w in zip(ais_out.terminals, ais_out.normw):
        # x_state is a State: list[ProfilePart], aligned with profiles 0..K-1
        for k in range(K):
            idxs = prof_to_global[k]
            if not idxs: 
                continue

            # Partition matrix for this profile from the state
            Bk = x_state[k].B  # compact sigma for profile k (or None)
            # If None: no interior cuts -> one pool; still works with extract_pools
            # Build pools & policy→pool mapping for this profile's policy list
            sigma_full_k = assemble_sigma_full_for_profile(x_state[k], M, R_per)   # <-- NEW

            pi_pools_k, pi_policies_k = extract_pools.extract_pools(prof_policies[k], sigma_full_k, lattice_edges)

            # Compute pool means using the *per-profile* policy_means slice
            mu_pools_k = loss.compute_pool_means(prof_means_arr[k], pi_pools_k)

            # Write predictions back to global positions, weighted by particle weight
            for local_idx, pid in enumerate(idxs):
                pool_id = pi_policies_k[local_idx ]  # map policy→pool
                mu_hat[pid] += w * mu_pools_k[pool_id]

    return mu_hat


# ---------- 2) quick comparison against data-generation truth ----------

def compare_estimates_to_truth(mu_hat, true_mu_per_policy, top_n=10):
    """
    Returns a dict with MAE/RMSE and a small table of the largest absolute errors.
    """
    diff = mu_hat - true_mu_per_policy
    mae  = float(np.mean(np.abs(diff)))
    rmse = float(np.sqrt(np.mean(diff**2)))

    # top errors
    order = np.argsort(-np.abs(diff))[:top_n]
    table = [
        {"policy_id": int(i), "mu_hat": float(mu_hat[i]),
         "mu_true": float(true_mu_per_policy[i]), "abs_err": float(abs(diff[i]))}
        for i in order
    ]
    return {"MAE": mae, "RMSE": rmse, "top_abs_errors": table}


In [78]:
# 1) get AIS posterior-averaged predictions per policy
mu_hat = estimate_policy_means_from_ais(
    ais_out=out,                 # from your run_ais_state
    all_policies=all_policies,
    policy_means=policy_means,
    prof_idx_of_policy=prof_idx_of_policy,
    lattice_edges=None,                  # or the hasse edges if you use them
    R_per = R,
    M=M
)

# 2) compare to the ground truth from your data generator
true_mu_per_policy = policy_means[:,0] / policy_means[:,1]
report = compare_estimates_to_truth(mu_hat, true_mu_per_policy, top_n=10)
print("MAE:", report["MAE"], "RMSE:", report["RMSE"])
for row in report["top_abs_errors"]:
    print(row)


MAE: 0.7145069566524032 RMSE: 0.8948789130808001
{'policy_id': 11, 'mu_hat': -0.02728615109187363, 'mu_true': 1.9970958848620424, 'abs_err': 2.024382035953916}
{'policy_id': 20, 'mu_hat': -0.02728615109187363, 'mu_true': -1.9957161271792738, 'abs_err': 1.9684299760874002}
{'policy_id': 29, 'mu_hat': -0.11450468016975583, 'mu_true': -1.9941461819093675, 'abs_err': 1.8796415017396118}
{'policy_id': 15, 'mu_hat': -1.2832557521354506, 'mu_true': 0.0010817274937654623, 'abs_err': 1.2843374796292162}
{'policy_id': 12, 'mu_hat': -1.28298931744374, 'mu_true': 0.0009133709267586914, 'abs_err': 1.2839026883704985}
{'policy_id': 7, 'mu_hat': -0.2033496781889139, 'mu_true': 1.007952481620198, 'abs_err': 1.2113021598091118}
{'policy_id': 8, 'mu_hat': -0.7856852130824112, 'mu_true': -1.996842478694527, 'abs_err': 1.2111572656121157}
{'policy_id': 5, 'mu_hat': -0.7859471517201148, 'mu_true': -1.991787251536953, 'abs_err': 1.2058400998168382}
{'policy_id': 4, 'mu_hat': -0.2048871423457377, 'mu_true': 

In [ ]:
cfg = AISConfig(n_paths=100, n_levels=5, moves_per_level=5, min_len=1, seed=2)
# out_100 = run_ais_state(
#     anchors=R_set,          # not used by q0, but you may keep for consistency
#     score_s=score_s,        # returns exp(-loss(state)) or similar
#     cfg=cfg,
#     RPS=RPS_states,              # your Rashomon partitions as a list of State
#     R_per=R,  # levels per arm (includes control)
#     eps1=0.05, eps2=0.25
# )

-28.77544598307075
-6.13122648948314
-29.665736293991333
-6.13122648948314
-29.66573471360918
-6.13122648948314
-30.540462888317503
-6.818924065275522
-28.77544598307075
-6.13122648948314
-30.775443437104407
-6.818924065275522
-26.992917023922892
-6.13122648948314
-29.775443810029778
-6.818924065275522
-27.417693205043694
-6.13122648948314
-29.665736293991333
-6.13122648948314
-30.665734670545987
-6.818924065275522
-31.773166186975484
-11.374888700286578
-25.32939305505206
-6.13122648948314
-27.86536734183948
-6.818924065275522
-26.204121229760382
-6.818924065275522
-26.204121229760382
-6.818924065275522
-27.437518357674058
-6.13122648948314
-28.437516734228716
-6.818924065275522
-28.437516734228716
-6.818924065275522
-28.437516734228716
-6.818924065275522
-26.990639167131157
-6.13122648948314
-29.773165953238042
-6.818924065275522
-30.103139012371287
-11.374888700286578
-33.87961587951739
-11.374888700286578
-29.665734164013553
-6.13122648948314
-30.775443437104407
-6.818924065275522


In [81]:
# 1) get AIS posterior-averaged predictions per policy
mu_hat = estimate_policy_means_from_ais(
    ais_out=out_100,                 # from your run_ais_state
    all_policies=all_policies,
    policy_means=policy_means,
    prof_idx_of_policy=prof_idx_of_policy,
    lattice_edges=None,                  # or the hasse edges if you use them
    R_per = R,
    M=M
)

# 2) compare to the ground truth from your data generator
true_mu_per_policy = policy_means[:,0] / policy_means[:,1]
report = compare_estimates_to_truth(mu_hat, true_mu_per_policy, top_n=10)
print("MAE:", report["MAE"], "RMSE:", report["RMSE"])
for row in report["top_abs_errors"]:
    print(row)

MAE: 0.6504034454877723 RMSE: 0.7571261918904078
{'policy_id': 11, 'mu_hat': 0.4747326641185874, 'mu_true': 1.9970958848620424, 'abs_err': 1.522363220743455}
{'policy_id': 20, 'mu_hat': -0.5087924631506813, 'mu_true': -1.9957161271792738, 'abs_err': 1.4869236640285926}
{'policy_id': 29, 'mu_hat': -0.5575319164432156, 'mu_true': -1.9941461819093675, 'abs_err': 1.4366142654661518}
{'policy_id': 9, 'mu_hat': 0.9355945029791992, 'mu_true': -0.0005622615477594285, 'abs_err': 0.9361567645269586}
{'policy_id': 14, 'mu_hat': 1.0789795810752185, 'mu_true': 1.9987777707820387, 'abs_err': 0.9197981897068201}
{'policy_id': 13, 'mu_hat': 0.9169310994652591, 'mu_true': -0.0009261142819823455, 'abs_err': 0.9178572137472414}
{'policy_id': 16, 'mu_hat': 0.9169328719523547, 'mu_true': -0.0006327396894168602, 'abs_err': 0.9175656116417716}
{'policy_id': 17, 'mu_hat': 1.0789895080992442, 'mu_true': 1.991348225901597, 'abs_err': 0.9123587178023529}
{'policy_id': 15, 'mu_hat': -0.8709635538219802, 'mu_true'

In [83]:
len(out_100.normw)

100

In [ ]:
cfg = AISConfig(n_paths=300, n_levels=5, moves_per_level=5, min_len=1, seed=2)
# out_300 = run_ais_state(
#     anchors=R_set,          # not used by q0, but you may keep for consistency
#     score_s=score_s,        # returns exp(-loss(state)) or similar
#     cfg=cfg,
#     RPS=RPS_states,              # your Rashomon partitions as a list of State
#     R_per=R,  # levels per arm (includes control)
#     eps1=0.05, eps2=0.25
# )

-28.77544598307075
-6.13122648948314
-29.665736293991333
-6.13122648948314
-29.66573471360918
-6.13122648948314
-30.540462888317503
-6.818924065275522
-28.77544598307075
-6.13122648948314
-30.775443437104407
-6.818924065275522
-26.992917023922892
-6.13122648948314
-29.775443810029778
-6.818924065275522
-27.417693205043694
-6.13122648948314
-29.665736293991333
-6.13122648948314
-30.665734670545987
-6.818924065275522
-31.773166186975484
-11.374888700286578
-25.32939305505206
-6.13122648948314
-27.86536734183948
-6.818924065275522
-26.204121229760382
-6.818924065275522
-26.204121229760382
-6.818924065275522
-27.437518357674058
-6.13122648948314
-28.437516734228716
-6.818924065275522
-28.437516734228716
-6.818924065275522
-28.437516734228716
-6.818924065275522
-26.990639167131157
-6.13122648948314
-29.773165953238042
-6.818924065275522
-30.103139012371287
-11.374888700286578
-33.87961587951739
-11.374888700286578
-29.665734164013553
-6.13122648948314
-30.775443437104407
-6.818924065275522


In [86]:
# 1) get AIS posterior-averaged predictions per policy
mu_hat = estimate_policy_means_from_ais(
    ais_out=out_300,                 # from your run_ais_state
    all_policies=all_policies,
    policy_means=policy_means,
    prof_idx_of_policy=prof_idx_of_policy,
    lattice_edges=None,                  # or the hasse edges if you use them
    R_per = R,
    M=M
)

# 2) compare to the ground truth from your data generator
true_mu_per_policy = policy_means[:,0] / policy_means[:,1]
report = compare_estimates_to_truth(mu_hat, true_mu_per_policy, top_n=10)
print("MAE:", report["MAE"], "RMSE:", report["RMSE"])
for row in report["top_abs_errors"]:
    print(row)

MAE: 0.6487053655804175 RMSE: 0.7700263320362413
{'policy_id': 11, 'mu_hat': 0.257989247199114, 'mu_true': 1.9970958848620424, 'abs_err': 1.7391066376629283}
{'policy_id': 20, 'mu_hat': -0.2885303957766256, 'mu_true': -1.9957161271792738, 'abs_err': 1.7071857314026482}
{'policy_id': 29, 'mu_hat': -0.5434444054413895, 'mu_true': -1.9941461819093675, 'abs_err': 1.450701776467978}
{'policy_id': 28, 'mu_hat': 0.02529134650827967, 'mu_true': 0.9997474136281175, 'abs_err': 0.9744560671198378}
{'policy_id': 15, 'mu_hat': -0.9058922608842369, 'mu_true': 0.0010817274937654623, 'abs_err': 0.9069739883780024}
{'policy_id': 12, 'mu_hat': -0.9056368325579134, 'mu_true': 0.0009133709267586914, 'abs_err': 0.9065502034846721}
{'policy_id': 14, 'mu_hat': 1.095396720139702, 'mu_true': 1.9987777707820387, 'abs_err': 0.9033810506423368}
{'policy_id': 13, 'mu_hat': 0.9006343230954745, 'mu_true': -0.0009261142819823455, 'abs_err': 0.9015604373774568}
{'policy_id': 16, 'mu_hat': 0.9006462103266627, 'mu_true'

In [96]:
def count_unique_states(ais_out) -> int:
    """Return the number of unique states in ais_out.terminals."""
    seen = set()
    for s in ais_out.terminals:
        seen.add(_state_signature(s))
    return len(seen)

count_unique_states(out_100)

94

### Comparing AIS posterior estimate with MCMC

In [115]:
import math, random, numpy as np
from collections import defaultdict
from typing import List, Dict, Tuple

# --- small helpers (match your existing conventions) ---
def init_from_RPS(RPS: List, log_alpha: List[float], rng: np.random.Generator) -> List:
    p = _softmax_logalpha(log_alpha)
    return _copy_state(RPS[rng.choice(len(RPS), p=p)])

# --- one MH step targeting the true posterior p(x) ∝ score_s(x) ---
def mh_step_true_posterior(x, score_s, min_len=1):
    N_cur = [n for n in state_neighbors_ubs(x, min_len=min_len) if not states_equal(n, x)]
    if not N_cur: 
        return x, 0
    prop = random.choice(N_cur)
    N_prop = [n for n in state_neighbors_ubs(prop, min_len=min_len) if not states_equal(n, prop)]
    lcur = math.log(max(1e-300, score_s(x)))
    lprop = math.log(max(1e-300, score_s(prop)))
    # uniform-neighbor proposal → include degree correction
    logr = (lprop - lcur) + math.log(max(1, len(N_cur))) - math.log(max(1, len(N_prop)))
    if math.log(random.random() + 1e-300) < min(0.0, logr):
        return prop, 1
    return x, 0

# --- single chain ---
def run_mcmc_chain(score_s,
                   RPS: List, log_alpha: List[float],
                   steps=20000, burnin=2000, thin=10,
                   seed=0, min_len=1):
    np.random.seed(seed); random.seed(seed)
    rng = np.random.default_rng(seed)

    x = init_from_RPS(RPS, log_alpha, rng)  # start in RPS (loss-weighted)
    accepts = 0
    samples = []

    for t in range(steps):
        x, acc = mh_step_true_posterior(x, score_s, min_len=min_len)
        accepts += acc
        if t >= burnin and ((t - burnin) % thin == 0):
            samples.append(_copy_state(x))

    acc_rate = accepts / max(1, steps)
    return samples, acc_rate

# --- multiple chains + aggregation to a posterior over states ---
def run_mcmc(score_s, RPS, log_alpha,
             n_chains=8, steps=20000, burnin=2000, thin=10,
             seed=0, min_len=1):
    all_samples = []
    acc_rates = []
    for c in range(n_chains):
        samples, ar = run_mcmc_chain(score_s, RPS, log_alpha,
                                     steps=steps, burnin=burnin, thin=thin,
                                     seed=seed + 31*c, min_len=min_len)
        all_samples.extend(samples)
        acc_rates.append(ar)
    # empirical posterior over unique states
    counts = defaultdict(int)
    for s in all_samples:
        counts[_state_signature(s)] += 1
    total = sum(counts.values())
    post = {sig: cnt/total for sig, cnt in counts.items()}
    return {"samples": all_samples,
            "acc_rate_mean": float(np.mean(acc_rates)),
            "acc_rate_sd": float(np.std(acc_rates)),
            "posterior": post}

# --- optional: compare MCMC posterior to AIS posterior (over shared support) ---
def ais_posterior_over_signatures(ais_out) -> Dict[Tuple, float]:
    w_by_sig = defaultdict(float)
    for s, w in zip(ais_out.terminals, ais_out.normw):
        w_by_sig[_state_signature(s)] += float(w)
    Z = sum(w_by_sig.values())
    return {sig: w/Z for sig, w in w_by_sig.items()} if Z>0 else {}

def tv_distance(p: Dict[Tuple,float], q: Dict[Tuple,float]) -> float:
    keys = set(p) | set(q)
    return 0.5 * sum(abs(p.get(k,0.0) - q.get(k,0.0)) for k in keys)

# Example usage:
# mcmc_res = run_mcmc(score_s, RPS_states, log_alpha, n_chains=8, steps=30000, burnin=5000, thin=10, seed=1, min_len=1)
# mcmc_post = mcmc_res["posterior"]
# ais_post = ais_posterior_over_signatures(ais_out)
# print("Mean acc rate:", mcmc_res["acc_rate_mean"])
# print("TV distance(AIS, MCMC):", tv_distance(ais_post, mcmc_post))


In [116]:
log_alpha = [score_s(A) for A in anchors]
mcmc_res = run_mcmc(score_s, RPS_states, log_alpha, n_chains=8, steps=300, burnin=50, thin=2, seed=1, min_len=1)

In [117]:
ais_post = ais_posterior_over_signatures(out_300)
print("TV distance(AIS, MCMC):", tv_distance(ais_post, mcmc_res["posterior"]))

TV distance(AIS, MCMC): 0.9507211792766872


In [118]:
mcmc_res["posterior"].values()

dict_values([0.001, 0.002, 0.002, 0.005, 0.001, 0.001, 0.01, 0.004, 0.001, 0.001, 0.002, 0.001, 0.001, 0.001, 0.001, 0.003, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.003, 0.001, 0.001, 0.002, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.003, 0.003, 0.001, 0.001, 0.001, 0.002, 0.001, 0.001, 0.002, 0.001, 0.001, 0.002, 0.002, 0.003, 0.001, 0.003, 0.005, 0.002, 0.01, 0.001, 0.001, 0.002, 0.001, 0.001, 0.001, 0.001, 0.002, 0.002, 0.006, 0.003, 0.008, 0.001, 0.001, 0.001, 0.001, 0.002, 0.001, 0.001, 0.001, 0.001, 0.002, 0.001, 0.002, 0.002, 0.003, 0.004, 0.003, 0.002, 0.002, 0.002, 0.003, 0.001, 0.002, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.002, 0.003, 0.002, 0.001, 0.001, 0.003, 0.002, 0.003, 0.001, 0.001, 0.003, 0.005, 0.001, 0.001, 0.001, 0.001, 0.002, 0.002, 0.003, 0.001, 0.001, 0.001, 0.004, 0.003, 0.003, 0.001, 0.003, 0.001, 0.001, 0.

### Pilot run to determine parameters in AIS, aiming for ESS>0.8 at each step

In [48]:
import math, random, numpy as np
from typing import Callable, List, Tuple, Optional

# Types:
# - State = List[ProfilePart]
# You already have: mh_step_state_uniform_neighbors(x, beta, log_q0, score_s, min_len)

def _logp(state, score_s: Callable) -> float:
    return math.log(max(1e-300, float(score_s(state))))

def _ess_from_logw(logw: np.ndarray) -> float:
    """ESS for *incremental* weights; returns ESS count (not ratio)."""
    m = float(np.max(logw))
    w = np.exp(logw - m)
    Z = w.sum()
    if Z <= 0: return 0.0
    w /= Z
    return 1.0 / float(np.sum(w*w))

def _normalize_logw(logw: np.ndarray) -> np.ndarray:
    m = float(np.max(logw)); w = np.exp(logw - m); s = w.sum()
    return w / s if s > 0 else np.full_like(w, 1.0 / len(w))

def pilot_adaptive_ladder(
    init_sampler: Callable[[int], List],         # returns a list of N initial States ~ q0 (or your RPS-init)
    log_q0: Callable[[List], float],             # log q0(x)
    score_s: Callable[[List], float],            # unnormalized target (positive), log taken inside
    N: int = 512,                                # probe particle count
    ess_target: float = 0.80,                    # target ESS ratio per step (0.7–0.9 typical)
    beta0: float = 0.0, beta1: float = 1.0,      # bridge endpoints
    initial_delta: float = 0.10,                 # starting step size Δβ
    min_delta: float = 1e-3,                     # do not split below this Δβ
    max_levels: int = 1000,                      # safety cap
    moves_per_probe: int = 0,                    # optional light mixing at each accepted β
    min_len: int = 1,                            # passed to your MH move
    rng_seed: Optional[int] = 1234
) -> Tuple[np.ndarray, List[float]]:
    """
    Returns:
      ladder: np.array of β's including endpoints (monotone, starts at beta0, ends at beta1)
      ess_ratios: list of ESS/N achieved at each accepted step (len = len(ladder)-1)
    Behavior:
      - Inserts rungs by halving Δβ whenever ESS/N < ess_target.
      - After accepting a step, does multinomial resample and (optional) a few MH moves at that β.
    """
    if rng_seed is not None:
        np.random.seed(rng_seed); random.seed(rng_seed)

    # 1) initialize probe particles ~ q0 (or your RPS init) with equal weights
    X = init_sampler(N)                 # list of N States
    beta = beta0
    ladder = [beta0]
    ess_ratios = []
    step = 0
    delta = initial_delta

    # Precompute logp−logq0 for efficiency (updated only after moves)
    logp_minus_logq = np.array([_logp(x, score_s) - float(log_q0(x)) for x in X], dtype=float)

    while beta < beta1 - 1e-12 and len(ladder) < max_levels:
        beta_try = min(beta + delta, beta1)
        d = beta_try - beta
        # 2) incremental log-weights for proposed step
        inc_logw = d * logp_minus_logq
        ess = _ess_from_logw(inc_logw)            # ESS count
        ess_ratio = ess / float(N)

        if ess_ratio < ess_target and d > min_delta:
            # too steep → split step
            delta *= 0.5
            continue

        # 3) accept this rung
        ladder.append(beta_try)
        ess_ratios.append(float(ess_ratio))

        # 4) resample to equal weights (multinomial); this stabilizes chaining of probe steps
        nw = _normalize_logw(inc_logw)
        idx = np.random.choice(N, size=N, p=nw)
        X = [X[i] for i in idx]
        logp_minus_logq = logp_minus_logq[idx]    # keep aligned

        # 5) optional light mixing at β_try so the next probe is representative
        if moves_per_probe > 0:
            for i in range(N):
                xi = X[i]
                for _ in range(moves_per_probe):
                    xi = mh_step_state_uniform_neighbors(
                        xi, t=beta_try, log_q0=log_q0, score_s=score_s, min_len=min_len
                    )
                X[i] = xi
            # refresh logp−logq0 after moves
            logp_minus_logq = np.array([_logp(x, score_s) - float(log_q0(x)) for x in X], dtype=float)

        # 6) advance
        beta = beta_try
        # adjust next delta mildly (optional heuristic): grow if easy, shrink if tight
        if ess_ratio > max(ess_target, 0.9):
            delta = min(2*delta, beta1 - beta)    # speed up a bit on easy segments
        else:
            # keep current delta unless we barely passed (no change)
            delta = min(delta, beta1 - beta)
        step += 1

        if beta >= beta1 - 1e-12:
            break

    # ensure endpoint
    if ladder[-1] < beta1:
        ladder.append(beta1)

    return np.asarray(ladder, float), ess_ratios


In [53]:
# 1) Your init sampler: start from RPS using existing log_alpha weights
def init_from_RPS_batch(RPS, log_alpha, batch_N, rng_seed=None):
    if rng_seed is not None:
        np.random.seed(rng_seed); random.seed(rng_seed)
    # softmax over log_alpha
    z = np.asarray(log_alpha, float); m = float(z.max()); p = np.exp(z-m); p /= p.sum()
    idx = np.random.choice(len(RPS), size=batch_N, p=p)
    def _copy_state(x):
        out=[]; 
        for pp in x:
            cov = None if pp.cov_ids is None else tuple(pp.cov_ids)
            if pp.B is None: Bc=None
            else:
                arr = np.asarray(pp.B)
                Bc = arr.copy() if isinstance(pp.B, np.ndarray) else [np.asarray(r).copy() for r in pp.B]
            out.append(type(pp)(cov_ids=cov, B=Bc))
        return out
    return [_copy_state(RPS[i]) for i in idx]

# 2) Build q0 buckets (weighted S0) once
log_alpha = [score_s(A) for A in anchors]

buckets = make_q0_buckets_weighted_S0(RPS_states, np.asarray(R,int), log_alpha,
                                      eps1=0.05, eps2=0.25, min_len=1)
log_q0 = lambda z: log_q0_distance_weighted_S0(z, buckets)

# 3) Run pilot
ladder, ess_ratios = pilot_adaptive_ladder(
    init_sampler=lambda N: init_from_RPS_batch(RPS_states, log_alpha, N, rng_seed=777),
    log_q0=log_q0,
    score_s=score_s,
    N=512,
    ess_target=0.80,
    beta0=0.0, beta1=1.0,
    initial_delta=0.10,
    min_delta=1e-3,
    moves_per_probe=3,   # small mixing at each accepted β (optional)
    min_len=1,
    rng_seed=777
)
print("Adaptive ladder has", len(ladder), "levels; first 10:", ladder[:10])
print("Per-step ESS ratios (len =", len(ess_ratios), "):", ess_ratios[:10])


Adaptive ladder has 9 levels; first 10: [0.  0.1 0.3 0.4 0.5 0.6 0.7 0.8 1. ]
Per-step ESS ratios (len = 8 ): [0.9793077629545456, 0.8412435919359166, 0.9503824895637129, 0.9409279607665507, 0.944596285723487, 0.939965249724696, 0.940602687271366, 0.8290601384679266]
